### ISSUE TITLE
TO-DO List 

### ISSUE THREAD

**Issue by Mr-krishn** [Ishan-Chanuka/TodoList-HTML-Hactoberfest#2]
hello @Ishan-Chanuka  i can design todo list in the web page , can u just assign me this task and also label with hactoberfest to this issue.

**Comment by anushkapal28** [comment]
"Hello! I'm interested in working on this task. I have experience with HTML and CSS, and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks!"

**Comment by Mr-krishn** [comment]
.
